export const slides = [
  {
    id: 0,
    title: 'SUMMER SALES',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    img_url: "https://www.pngarts.com/files/2/Model-PNG-Picture-1.png",
    bg: "#f5fafd"
  },
  {
    id: 1,
    title: 'Winter SALES',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    img_url: "https://www.pngarts.com/files/2/Model-PNG-Image-Transparent.png",
    bg: "#fcf1ed"
  },
  {
    id: 2,
    title: 'Popular SALES',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    description: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS",
    img_url: "https://www.pngarts.com/files/2/Model-PNG-Background-Image.png",
    bg: "#fbf0f4"
  },
]


export const categories = [
  {
    id: 0,
    title: 'SHIRT STYLE!',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://images.pexels.com/photos/5886041/pexels-photo-5886041.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    cat: 't-shirts'
  },
  {
    id: 1,
    title: 'LOUNGEWEAR LOVE',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    cat: 'hoodies'
  },
  {
    id: 2,
    title: 'LIGHT JACKETS',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img_url: "https://images.pexels.com/photos/5480696/pexels-photo-5480696.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    cat: 'jackets'
  },
]

export const popularProducts = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    cat: 't-shirts',
    size: ['xs', 'm', 'l'],
    color: ['red', 'black', 'white', 'orange'],
    stock: 25,
    price: 10,
  },
  {
    id: 2,
    title: 'T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/T-Shirt-Transparent-Background-PNG.png",
    cat: 't-shirts',
    size: ['l', 'xl'],
    color: ['indianred', 'black',],
    stock: 14,
    price: 8,
  },
  {
    id: 8,
    title: 'Woman Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    cat: 'jackets',
    size: ['s', 'm'],
    color: ['white', 'sandybrown'],
    stock: 12,
    price: 80,
  },
  {
    id: 9,
    title: 'Hoodie',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Black-Hoodie-Pullover-PNG-Transparent-Photo.png",
    cat: 'hoodies',
    size: ['xs', 's', 'm'],
    color: ['black', 'white'],
    stock: 18,
    price: 35,
  },
  {
    id: 10,
    title: 'Hoodie',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Black-Hoodie-Pullover-PNG-No-Background.png",
    cat: 'hoodies',
    size: ['m', 'xl'],
    color: ['black', 'white', 'gray'],
    stock: 7,
    price: 30,
  },
  {
    id: 11,
    title: 'Basic T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/17/Halloween-T-Shirt-PNG-HQ-Picture.png",
    cat: 't-shirts',
    size: ['xs'],
    color: ['orangered', 'black', 'white'],
    stock: 12,
    price: 20,
  },
  {
    id: 12,
    title: 'Rounded T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/11/Boys-Yellow-T-Shirt-PNG-Image-Background.png",
    cat: 't-shirts',
    size: ['xs', 's', 'm', 'l'],
    color: ['white', 'yellow'],
    stock: 21,
    price: 25,
  },
  {
    id: 13,
    title: 'Basic T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Black-T-Shirt-Transparent-Images.png",
    cat: 't-shirts',
    size: ['s', 'm', 'l'],
    color: ['black', 'white',],
    stock: 9,
    price: 15,
  },
  {
    id: 14,
    title: 'Leather Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Jacket-PNG-Pic.png",
    cat: 'jackets',
    size: ['xs', 'l'],
    color: ['darkorange'],
    stock: 37,
    price: 120,
  },
  {
    id: 15,
    title: 'WaterProof Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Jacket-PNG-Download-Image.png",
    cat: 'jackets',
    size: ['xs', 'm',],
    color: ['black', 'white', 'orange'],
    stock: 14,
    price: 140,
  },
  {
    id: 16,
    title: 'WaterProof Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Blue-Jacket-PNG-Free-Download.png",
    cat: 'jackets',
    size: ['m', 'l', 'xl'],
    color: ['white', 'lightblue'],
    stock: 41,
    price: 220,
  },
  {
    id: 17,
    title: 'Leather Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Ladies-Jacket-PNG-Photo.png",
    cat: 'jackets',
    size: ['xs', 's', 'l'],
    color: ['white', 'lightblue'],
    stock: 27,
    price: 150,
  },
  {
    id: 18,
    title: 'Men Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Women-Leather-Jacket-PNG-Pic.png",
    cat: 'jackets',
    size: ['m', 'l', 'xl'],
    color: ['rosybrown', 'black'],
    stock: 17,
    price: 100,

  },
  {
    id: 19,
    title: 'WaterProof Woman Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Pink-Jacket-For-Women-Transparent-Image.png",
    cat: 'jackets',
    size: ['xs', 's', 'm', 'xl'],
    color: ['black', 'deeppink'],
    stock: 10,
    price: 140,
  },
  {
    id: 20,
    title: 'WaterProof Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Hooded-Jacket-Men-PNG-Transparent-Image.png",
    cat: 'jackets',
    size: ['s', 'm', 'l'],
    color: ['black',],
    stock: 19,
    price: 200,
  },
  {
    id: 21,
    title: 'Men Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Leather-Jacket-PNG-Transparent-Image.png",
    cat: 'jackets',
    size: ['xs', 's', 'm'],
    color: ['black', 'brown'],
    stock: 11,
    price: 350,
  },
  {
    id: 22,
    title: 'Men Jacket',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/4/Bomber-Jacket-PNG-Image.png",
    cat: 'jackets',
    size: ['s', 'm', 'l',],
    color: ['black'],
    stock: 58,
    price: 275,
  },
  {
    id: 23,
    title: 'Black Hoodie',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/9/Black-Hoodie-Front-PNG-HD-Photo.png",
    cat: 'hoodies',
    size: ['s', 'm'],
    color: ['black'],
    stock: 13,
    price: 90,
  },
  {
    id: 24,
    title: 'Polo Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/4/Polo-Shirt-PNG-Image-Transparent.png",
    cat: 't-shirts',
    size: ['s', 'l'],
    color: ['white', 'orange'],
    stock: 25,
    price: 50,
  },
  {
    id: 25,
    title: 'Basic T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/17/Halloween-T-Shirt-PNG-Photo-HQ.png",
    cat: 't-shirts',
    size: ['xs', 's', 'm', 'l', 'xl'],
    color: ['black'],
    stock: 25,
    price: 35,
  },
  {
    id: 26,
    title: "Jogger Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Shoes-Download-PNG-Image.png",
    cat: 'shoes',
    size: [40, 41, 42, 43, 44, 45,],
    color: ['gray', 'black',],
    stock: 25,
    price: 70,
  },
  {
    id: 27,
    title: "Jogger Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/1/Women-Casual-Shoes-PNG-Image-Background.png",
    cat: 'shoes',
    size: [36, 37, 39, 41],
    color: ['white', 'deeppink'],
    stock: 25,
    price: 55,
  },
  {
    id: 28,
    title: "Gucci Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/2/Gucci-Shoes-For-Women-Transparent-Image.png",
    cat: 'shoes',
    size: [41, 42,],
    color: ['black', 'white'],
    stock: 25,
    price: 420,
  },
  {
    id: 29,
    title: "Jogger Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Jogger-Shoes-PNG-Download-Image.png",
    cat: 'shoes',
    size: [40, 41, 42, 43, 44],
    color: ['white', 'blue'],
    stock: 25,
    price: 110,
  },
  {
    id: 30,
    title: "Nike Running Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Nike-Running-Shoes-Free-PNG-Image.png",
    cat: 'shoes',
    size: [40, 41, 42, 43, 45],
    color: ['red', 'dodgerblue',],
    stock: 25,
    price: 60,
  },
  {
    id: 31,
    title: "Adidas Running Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Adidas-Running-Shoes-PNG-Image.png",
    cat: 'shoes',
    size: [39, 41, 42, 43, 44],
    color: ['red', 'black'],
    stock: 14,
    price: 50,
  },
  {
    id: 32,
    title: "Woman Running Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/3/Women-Running-Shoes-Download-PNG-Image.png",
    cat: 'shoes',
    size: [37, 38, 39],
    color: ['blue', 'pink'],
    stock: 37,
    price: 35,
  },

  {
    id: 34,
    title: "Adidas Running Shoes",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/5/Adidas-Shoes-PNG-Image.png",
    cat: 'shoes',
    size: [37, 41, 44],
    color: ['darkblue'],
    stock: 7,
    price: 85,
  },
  {
    id: 35,
    title: "Air Force",
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
    img: "https://www.pngarts.com/files/8/Air-Force-One-White-Nike-Shoes-PNG-Picture.png",
    cat: 'shoes',
    size: [37, 38, 39, 40, 42, 44],
    color: ['white',],
    stock: 33,
    price: 190,
  },
]


const test = async () => {
  const popularProducts = [
    {
      title: 'Basic T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
      category: 't-shirts',
      size: ['xs', 'm', 'l'],
      color: ['red', 'black', 'white', 'orange'],
      stock: 25,
      price: 10,
    },
    {
      title: 'T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/T-Shirt-Transparent-Background-PNG.png",
      category: 't-shirts',
      size: ['l', 'xl'],
      color: ['indianred', 'black',],
      stock: 14,
      price: 8,
    },
    {
      title: 'Woman Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
      category: 'jackets',
      size: ['s', 'm'],
      color: ['white', 'sandybrown'],
      stock: 12,
      price: 80,
    },
    {
      title: 'Hoodie',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Black-Hoodie-Pullover-PNG-Transparent-Photo.png",
      category: 'hoodies',
      size: ['xs', 's', 'm'],
      color: ['black', 'white'],
      stock: 18,
      price: 35,
    },
    {
      title: 'Hoodie',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Black-Hoodie-Pullover-PNG-No-Background.png",
      category: 'hoodies',
      size: ['m', 'xl'],
      color: ['black', 'white', 'gray'],
      stock: 7,
      price: 30,
    },
    {
      title: 'Basic T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/17/Halloween-T-Shirt-PNG-HQ-Picture.png",
      category: 't-shirts',
      size: ['xs'],
      color: ['orangered', 'black', 'white'],
      stock: 12,
      price: 20,
    },
    {
      title: 'Rounded T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/11/Boys-Yellow-T-Shirt-PNG-Image-Background.png",
      category: 't-shirts',
      size: ['xs', 's', 'm', 'l'],
      color: ['white', 'yellow'],
      stock: 21,
      price: 25,
    },
    {
      title: 'Basic T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Black-T-Shirt-Transparent-Images.png",
      category: 't-shirts',
      size: ['s', 'm', 'l'],
      color: ['black', 'white',],
      stock: 9,
      price: 15,
    },
    {
      title: 'Leather Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Jacket-PNG-Pic.png",
      category: 'jackets',
      size: ['xs', 'l'],
      color: ['darkorange'],
      stock: 37,
      price: 120,
    },
    {
      title: 'WaterProof Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Jacket-PNG-Download-Image.png",
      category: 'jackets',
      size: ['xs', 'm',],
      color: ['black', 'white', 'orange'],
      stock: 14,
      price: 140,
    },
    {
      title: 'WaterProof Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Blue-Jacket-PNG-Free-Download.png",
      category: 'jackets',
      size: ['m', 'l', 'xl'],
      color: ['white', 'lightblue'],
      stock: 41,
      price: 220,
    },
    {
      title: 'Leather Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Ladies-Jacket-PNG-Photo.png",
      category: 'jackets',
      size: ['xs', 's', 'l'],
      color: ['white', 'lightblue'],
      stock: 27,
      price: 150,
    },
    {
      title: 'Men Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Women-Leather-Jacket-PNG-Pic.png",
      category: 'jackets',
      size: ['m', 'l', 'xl'],
      color: ['rosybrown', 'black'],
      stock: 17,
      price: 100,

    },
    {
      title: 'WaterProof Woman Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Pink-Jacket-For-Women-Transparent-Image.png",
      category: 'jackets',
      size: ['xs', 's', 'm', 'xl'],
      color: ['black', 'deeppink'],
      stock: 10,
      price: 140,
    },
    {
      title: 'WaterProof Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Hooded-Jacket-Men-PNG-Transparent-Image.png",
      category: 'jackets',
      size: ['s', 'm', 'l'],
      color: ['black',],
      stock: 19,
      price: 200,
    },
    {
      title: 'Men Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Leather-Jacket-PNG-Transparent-Image.png",
      category: 'jackets',
      size: ['xs', 's', 'm'],
      color: ['black', 'brown'],
      stock: 11,
      price: 350,
    },
    {
      title: 'Men Jacket',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/4/Bomber-Jacket-PNG-Image.png",
      category: 'jackets',
      size: ['s', 'm', 'l',],
      color: ['black'],
      stock: 58,
      price: 275,
    },
    {
      title: 'Black Hoodie',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/9/Black-Hoodie-Front-PNG-HD-Photo.png",
      category: 'hoodies',
      size: ['s', 'm'],
      color: ['black'],
      stock: 13,
      price: 90,
    },
    {
      title: 'Polo Shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/4/Polo-Shirt-PNG-Image-Transparent.png",
      category: 't-shirts',
      size: ['s', 'l'],
      color: ['white', 'orange'],
      stock: 25,
      price: 50,
    },
    {
      title: 'Basic T-shirt',
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/17/Halloween-T-Shirt-PNG-Photo-HQ.png",
      category: 't-shirts',
      size: ['xs', 's', 'm', 'l', 'xl'],
      color: ['black'],
      stock: 25,
      price: 35,
    },
    {
      title: "Jogger Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Shoes-Download-PNG-Image.png",
      category: 'shoes',
      size: [40, 41, 42, 43, 44, 45,],
      color: ['gray', 'black',],
      stock: 25,
      price: 70,
    },
    {
      title: "Jogger Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/1/Women-Casual-Shoes-PNG-Image-Background.png",
      category: 'shoes',
      size: [36, 37, 39, 41],
      color: ['white', 'deeppink'],
      stock: 25,
      price: 55,
    },
    {
      title: "Gucci Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/2/Gucci-Shoes-For-Women-Transparent-Image.png",
      category: 'shoes',
      size: [41, 42,],
      color: ['black', 'white'],
      stock: 25,
      price: 420,
    },
    {
      title: "Jogger Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Jogger-Shoes-PNG-Download-Image.png",
      category: 'shoes',
      size: [40, 41, 42, 43, 44],
      color: ['white', 'blue'],
      stock: 25,
      price: 110,
    },
    {
      title: "Nike Running Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Nike-Running-Shoes-Free-PNG-Image.png",
      category: 'shoes',
      size: [40, 41, 42, 43, 45],
      color: ['red', 'dodgerblue',],
      stock: 25,
      price: 60,
    },
    {
      title: "Adidas Running Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Adidas-Running-Shoes-PNG-Image.png",
      category: 'shoes',
      size: [39, 41, 42, 43, 44],
      color: ['red', 'black'],
      stock: 14,
      price: 50,
    },
    {
      title: "Woman Running Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/3/Women-Running-Shoes-Download-PNG-Image.png",
      category: 'shoes',
      size: [37, 38, 39],
      color: ['blue', 'pink'],
      stock: 37,
      price: 35,
    },

    {
      title: "Adidas Running Shoes",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/5/Adidas-Shoes-PNG-Image.png",
      category: 'shoes',
      size: [37, 41, 44],
      color: ['darkblue'],
      stock: 7,
      price: 85,
    },
    {
      title: "Air Force",
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores quos, sed provident perspiciatis, a placeat minus ab suscipit laudantium illo quam sapiente? Asperiores, eligendi molestiae dolores aspernatur, quia quod voluptatibus provident necessitatibus beatae magni recusandae quibusdam? Deserunt ipsum illo sed cupiditate optio impedit nam repellendus rem temporibus, placeat id iste.',
      img: "https://www.pngarts.com/files/8/Air-Force-One-White-Nike-Shoes-PNG-Picture.png",
      category: 'shoes',
      size: [37, 38, 39, 40, 42, 44],
      color: ['white',],
      stock: 33,
      price: 190,
    },
  ]
  for (const product of popularProducts) {
    const req = await fetch('http://127.0.0.1:1921/api/v1/product', {
      method: 'POST',
      headers: {
        "Content-type": "application/json"
      },
      body: JSON.stringify(product)
    })
    console.log(req)
  }
}